// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "[!output HEADER_FILE]"

/////////////////////////////////////////////////////////////////////////////
// [!output CLASS_NAME]

IMPLEMENT_DYNCREATE([!output CLASS_NAME], CWnd)

/////////////////////////////////////////////////////////////////////////////
// [!output CLASS_NAME] properties

/////////////////////////////////////////////////////////////////////////////
// [!output CLASS_NAME] operations
