// AddIn.idl : IDL source for AddIn
//

// This file will be processed by the MIDL tool to
// produce the type library (AddIn.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid($LIBID$),
	version(1.0),
	helpstring("$SAFEOBJNAME$ 1.0 Type Library")
]
library $SAFEOBJNAME$Lib
{
	importlib("stdole2.tlb");
	[
		uuid($ICONNECTCLSID$),
		helpstring("Connect Class")
	]
	coclass Connect
	{
		[default] interface IUnknown;
	};
};
