#pragma once

template <class T>
class CProxy_[!output INTERFACE_NAME]Events : public IConnectionPointImpl<T, &__uuidof(_[!output INTERFACE_NAME]Events), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
